import React from "react";
import type { Metadata } from "next";
import Navbar from "../../components/Navbar";
import { PluginProvider } from "../../lib/plugins";
import { PluginSlot } from "../../components/PluginSlot";
import { i18n, type Locale } from "../../i18n-config";
import LanguageProviderWrapper from "../../components/LanguageProviderWrapper";
import LanguageHtml from "../../components/LanguageHtml";
import LanguageDetectionToastContainer from "../../components/LanguageDetectionToast";

export const metadata: Metadata = {
    title: "Quicksilver Blog",
    description: "Purely static blog generated by Quicksilver CMS.",
};

export const dynamicParams = false;

export async function generateStaticParams() {
    return i18n.locales.map((lang: string) => ({ lang }));
}

export default async function LocaleLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ lang: string }>;
}>) {
    const { lang } = await params;
    return (
        <LanguageHtml lang={lang}>
            <LanguageProviderWrapper initialLanguage={lang}>
                <PluginProvider>
                    <Navbar lang={lang as Locale} />
                    <main className="container mx-auto flex-1 flex flex-col">
                        {children}
                    </main>
                    <PluginSlot name="footer-main" />
                    <LanguageDetectionToastContainer />
                </PluginProvider>
            </LanguageProviderWrapper>
        </LanguageHtml>
    );
}
